import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 min-h-screen">
        <nav className="w-full border-b border-gray-200 bg-white shadow-sm">
          <div className="container mx-auto flex items-center justify-between py-4 px-6">
            <div className="text-2xl font-bold tracking-tight">My Portfolio</div>
            <ul className="flex space-x-8 text-lg font-medium">
              <li><a href="#about" className="hover:text-gray-500 transition">About</a></li>
              <li><a href="#techstack" className="hover:text-gray-500 transition">Tech Stack</a></li>
              <li><a href="#experience" className="hover:text-gray-500 transition">Experience</a></li>
              <li><a href="#projects" className="hover:text-gray-500 transition">Projects</a></li>
              <li><a href="#contact" className="hover:text-gray-500 transition">Contact</a></li>
            </ul>
          </div>
        </nav>
        <main className="container mx-auto px-6 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
